# -*- coding: utf-8 -*-
"""LandMark Recognition App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_An5E1Ze32qYhPzWTSC4pvNovB-s9-63
"""

import tensorflow as tf
from tensorflow.keras import layers, Model
from tensorflow.keras.callbacks import EarlyStopping
import os, cv2, numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import json

MODEL_PATH = 'C:/Users/Lap.lk/Desktop/ML_VIVA/FineTuned-EfficientNetB0_CNN_Model.keras'
CLASS_NAMES_PATH = 'C:/Users/Lap.lk/Desktop/ML_VIVA/class_names.json'

LOCATION_MAP = {
    "Adam's Peak ": "Rathnapura, Sabaragamuwa Province, Sri Lanka ",
    "Ancient City of Polonnaruwa ": "Polonnaruwa, North Central Province, Sri Lanka ",
    "Beruwala Light House ": "Beruwala, Western Province, Sri Lanka ",
    "British War Cemetery ": "Kandy, Central Province, Sri Lanka ",
    "Bundala National Park ": "Hambantota, Southern Province, Sri Lanka ",
    "Delft Island ": "Jaffna, Northern Province, Sri Lanka ",
    "Dowa Rock Temple ": "Bandarawela, Uva Province, Sri Lanka ",
    "Ganagaramaya Temple ": "Colombo, Western Province, Sri Lanka ",
    "Henarathgoda Botanical Gard ": "Gampaha, Western Province, Sri Lanka ",
    "Hortains Plain ": "Nuwara Eliya, Central Province, Sri Lanka ",
    "Independance Square ": "Colombo, Western Province, Sri Lanka ",
    "Jaya Sri Maha Bodhi ": "Anuradhapura, North Central Province, Sri Lanka ",
    "Lotus Tower ": "Colombo, Western Province, Sri Lanka ",
    "Maligawa Buddha Statue ": "Kandy, Central Province, Sri Lanka ",
    "Nine Arches Bridge ": "Ella, Uva Province, Sri Lanka ",
    "Pinnawala Elephant Orphanage ": "Kegalle, Sabaragamuwa Province, Sri Lanka ",
    "Sigiriya ": "Matale, Central Province, Sri Lanka ",
    "Sinharaja Forest ": "Ratnapura, Sabaragamuwa Province, Sri Lanka ",
    "Sri Dalada Maligawa ": "Kandy, Central Province, Sri Lanka ",
    "Star Fort ": "Matara, Southern Province, Sri Lanka ",
    "Turtle Hatchery ": "Kosgoda, Southern Province, Sri Lanka ",
    "Vavuniya Archaeological Museum ": "Vavuniya, Northern Province, Sri Lanka ",
    "Wilapattu National Park ": "Puttalam, North Western Province, Sri Lanka ",
    "Yapahuwa Rock Fortress ": "Yapahuwa, North Western Province, Sri Lanka ",
}

class LandmarkClassifier:
    def __init__(self, model_path=MODEL_PATH, classes_path=CLASS_NAMES_PATH):
        self.model_path = model_path
        self.classes_path = classes_path
        self.model = None
        self.class_names = None
        self._load_model()

    def _load_model(self):
        if not os.path.exists(self.model_path):
            raise FileNotFoundError(f"Model file not found at {self.model_path}")
        if not os.path.exists(self.classes_path):
            raise FileNotFoundError(f"Class names file not found at {self.classes_path}")

        self.model = tf.keras.models.load_model(self.model_path)

        with open(self.classes_path, 'r') as f:
            self.class_names = json.load(f)

        print(f"✅ Model loaded from {self.model_path}")
        print(f"✅ Classes loaded: {len(self.class_names)} categories")

    def preprocess_image(self, image_input):
        if isinstance(image_input, str):
            img = Image.open(image_input).convert('RGB')
        elif isinstance(image_input, Image.Image):
            img = image_input.convert('RGB')
        else:
            raise ValueError("Input must be a file path string or PIL Image object")

        img_array = np.array(img)
        img_resized = cv2.resize(img_array, (290, 290))
        img_normalized = img_resized / 255.0
        img_batch = np.expand_dims(img_normalized, axis=0)
        return img_batch

    def predict(self, image_input):
        if self.model is None:
            raise RuntimeError("Model not loaded. Initialize LandmarkClassifier first.")

        img_batch = self.preprocess_image(image_input)
        predictions = self.model.predict(img_batch, verbose=0)
        pred_idx = np.argmax(predictions[0])

        landmark_name = self.class_names[pred_idx]
        location = LOCATION_MAP.get(landmark_name, "Unknown Location")

        return {
            'name': landmark_name,
            'place': location,
        }